[package]
name = "fs-utils"
version = "0.1.0"
authors = ["Sebastian Thiel <byronimo@gmail.com>"]
repository = "https://github.com/Byron/fs-utils-rs"
description = "Utilities to help working with the filesytem"
documentation = "https://byron.github.io/fs-utils-rs"
keywords = ["utility", "filesystem"]
license = "MIT OR Apache-2.0"

[dependencies]
quick-error = "1.1.0"

[dev-dependencies]
tempdir = "*"
